#!/usr/bin/env bash
# Installs Nginx on the server

# Update the package lists for upgrades and new package installations
sudo apt-get update -y

# Install Nginx
sudo apt-get install nginx -y

# Create a new Nginx server block with the configuration for listening on port 80
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Create a new HTML file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx to make the new configuration take effect
sudo service nginx restart
