#!/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

# Configure Nginx to use the custom 404 page
sudo sed -i 's|location / {|location / {\n        error_page 404 /custom_404.html;\n        try_files $uri $uri/ =404;|' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo systemctl restart nginx

