#!/usr/bin/env bash
# This script installs nginx if not installed and ensures it runs on port 80
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
