#!/usr/bin/env bash
# This script displays a list of all currently running processes in a user-oriented format with process hierarch
ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest
